import { Head, Html, Main, NextScript } from "next/document";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Document() {
  return (
    <Html lang="en">
      <Head />
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}

export default Document;
